// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7eovensldrSiUJw4CI9H3UYy5VI1e2Fg',
    appId: '1:628886293390:web:c20e117d690c9b7525f2df',
    messagingSenderId: '628886293390',
    projectId: 'monikid-bb66b',
    authDomain: 'monikid-bb66b.firebaseapp.com',
    storageBucket: 'monikid-bb66b.firebasestorage.app',
    measurementId: 'G-KK2GGGF72T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYec3Te0KnhhWsmLhZDjFRgauoTbeXvU',
    appId: '1:628886293390:android:f419265d592a926125f2df',
    messagingSenderId: '628886293390',
    projectId: 'monikid-bb66b',
    storageBucket: 'monikid-bb66b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBroV_uLdhq9DPuaieZf2kLnT-jyLD3Utw',
    appId: '1:628886293390:ios:d070afbb0da5238925f2df',
    messagingSenderId: '628886293390',
    projectId: 'monikid-bb66b',
    storageBucket: 'monikid-bb66b.firebasestorage.app',
    iosBundleId: 'com.example.monikid',
  );
}
