// ignore_for_file: avoid_hardcoded_locale

import 'package:monikid/models/entities/transaction_model.dart';

/// 30 mock transactions cho mục đích test / seed Firestore.
/// - userId & familyId placeholder: thay bằng giá trị thực khi seed.
/// - amountMinor tính bằng VND (không có decimal, đơn vị nhỏ nhất = 1 VND).
/// - type: 'expense' | 'income'
/// - source: 'manual' | 'ocr'
/// - evidenceImage bị bỏ qua theo yêu cầu.
const _userId = 'mock_user_001';
const _familyId = 'mock_family_001';

List<TransactionModel> get mockTransactions {
  final now = DateTime.now();
  final year = now.year;
  final month = now.month;

  return [
      // ── EXPENSE ──────────────────────────────────────────────
      TransactionModel(
        transactionId: 'txn_001',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 35000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'food_drink',
        categoryLabel: 'Ăn uống',
        categoryIcon: '🍜',
        note: 'Bún bò buổi sáng',
        source: 'manual',
        merchantName: 'Quán Bún Bò Huế 28',
        dateTs: DateTime(year, month, 1, 7, 30),
        createdAt: DateTime(year, month, 1, 7, 31),
        updatedAt: DateTime(year, month, 1, 7, 31),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_002',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 15000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'transport',
        categoryLabel: 'Di chuyển',
        categoryIcon: '🚌',
        note: 'Xe buýt đi học',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 1, 7, 0),
        createdAt: DateTime(year, month, 1, 7, 1),
        updatedAt: DateTime(year, month, 1, 7, 1),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_003',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 120000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'education',
        categoryLabel: 'Học tập',
        categoryIcon: '📚',
        note: 'Mua sách giáo khoa Toán 11',
        source: 'manual',
        merchantName: 'Nhà sách Fahasa',
        dateTs: DateTime(year, month, 2, 9, 0),
        createdAt: DateTime(year, month, 2, 9, 5),
        updatedAt: DateTime(year, month, 2, 9, 5),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_004',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 45000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'food_drink',
        categoryLabel: 'Ăn uống',
        categoryIcon: '🍜',
        note: 'Trà sữa sau giờ học',
        source: 'manual',
        merchantName: 'Gong Cha',
        dateTs: DateTime(year, month, 2, 15, 30),
        createdAt: DateTime(year, month, 2, 15, 32),
        updatedAt: DateTime(year, month, 2, 15, 32),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_005',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 250000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'entertainment',
        categoryLabel: 'Giải trí',
        categoryIcon: '🎮',
        note: 'Nạp game PUBG Mobile',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 3, 20, 0),
        createdAt: DateTime(year, month, 3, 20, 1),
        updatedAt: DateTime(year, month, 3, 20, 1),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_006',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 75000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'food_drink',
        categoryLabel: 'Ăn uống',
        categoryIcon: '🍜',
        note: 'Cơm trưa canteen trường',
        source: 'ocr',
        merchantName: 'Căng tin Trường THPT',
        dateTs: DateTime(year, month, 4, 12, 0),
        createdAt: DateTime(year, month, 4, 12, 5),
        updatedAt: DateTime(year, month, 4, 12, 5),
        ocrUsed: true,
        ocrConfidence: 0.91,
      ),
      TransactionModel(
        transactionId: 'txn_007',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 30000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'personal_care',
        categoryLabel: 'Chăm sóc cá nhân',
        categoryIcon: '💊',
        note: 'Mua thuốc cảm',
        source: 'manual',
        merchantName: 'Nhà thuốc Long Châu',
        dateTs: DateTime(year, month, 5, 17, 0),
        createdAt: DateTime(year, month, 5, 17, 2),
        updatedAt: DateTime(year, month, 5, 17, 2),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_008',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 500000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'clothing',
        categoryLabel: 'Quần áo',
        categoryIcon: '👕',
        note: 'Mua áo thun đồng phục thể dục',
        source: 'manual',
        merchantName: 'Canifa',
        dateTs: DateTime(year, month, 6, 14, 0),
        createdAt: DateTime(year, month, 6, 14, 10),
        updatedAt: DateTime(year, month, 6, 14, 10),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_009',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 20000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'transport',
        categoryLabel: 'Di chuyển',
        categoryIcon: '🚌',
        note: 'Grab đi học thêm',
        source: 'manual',
        merchantName: 'Grab',
        dateTs: DateTime(year, month, 7, 17, 45),
        createdAt: DateTime(year, month, 7, 17, 46),
        updatedAt: DateTime(year, month, 7, 17, 46),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_010',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 65000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'food_drink',
        categoryLabel: 'Ăn uống',
        categoryIcon: '🍜',
        note: 'Pizza với bạn bè',
        source: 'ocr',
        merchantName: 'Pizza 4P\'s',
        dateTs: DateTime(year, month, 8, 19, 0),
        createdAt: DateTime(year, month, 8, 19, 10),
        updatedAt: DateTime(year, month, 8, 19, 10),
        ocrUsed: true,
        ocrConfidence: 0.87,
      ),
      TransactionModel(
        transactionId: 'txn_011',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 150000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'education',
        categoryLabel: 'Học tập',
        categoryIcon: '📚',
        note: 'Phí học thêm Anh văn tháng 5',
        source: 'manual',
        merchantName: 'Trung tâm Anh ngữ Apax',
        dateTs: DateTime(year, month, 9, 8, 0),
        createdAt: DateTime(year, month, 9, 8, 5),
        updatedAt: DateTime(year, month, 9, 8, 5),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_012',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 100000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'entertainment',
        categoryLabel: 'Giải trí',
        categoryIcon: '🎬',
        note: 'Xem phim cuối tuần',
        source: 'manual',
        merchantName: 'CGV Vincom',
        dateTs: DateTime(year, month, 10, 15, 0),
        createdAt: DateTime(year, month, 10, 15, 5),
        updatedAt: DateTime(year, month, 10, 15, 5),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_013',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 55000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'food_drink',
        categoryLabel: 'Ăn uống',
        categoryIcon: '🍜',
        note: 'Phở bò sáng thứ 2',
        source: 'manual',
        merchantName: 'Phở Thìn',
        dateTs: DateTime(year, month, 12, 7, 0),
        createdAt: DateTime(year, month, 12, 7, 2),
        updatedAt: DateTime(year, month, 12, 7, 2),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_014',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 80000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'stationery',
        categoryLabel: 'Văn phòng phẩm',
        categoryIcon: '✏️',
        note: 'Mua vở, bút, thước',
        source: 'ocr',
        merchantName: 'Văn phòng phẩm Thiên Long',
        dateTs: DateTime(year, month, 13, 10, 0),
        createdAt: DateTime(year, month, 13, 10, 5),
        updatedAt: DateTime(year, month, 13, 10, 5),
        ocrUsed: true,
        ocrConfidence: 0.93,
      ),
      TransactionModel(
        transactionId: 'txn_015',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 200000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'personal_care',
        categoryLabel: 'Chăm sóc cá nhân',
        categoryIcon: '💇',
        note: 'Cắt tóc cuối tuần',
        source: 'manual',
        merchantName: 'Barber 30 Shine',
        dateTs: DateTime(year, month, 14, 9, 30),
        createdAt: DateTime(year, month, 14, 9, 35),
        updatedAt: DateTime(year, month, 14, 9, 35),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_016',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 40000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'snack',
        categoryLabel: 'Ăn vặt',
        categoryIcon: '🍿',
        note: 'Bắp rang + nước ngọt khi xem phim',
        source: 'manual',
        merchantName: 'CGV Vincom',
        dateTs: DateTime(year, month, 14, 15, 30),
        createdAt: DateTime(year, month, 14, 15, 31),
        updatedAt: DateTime(year, month, 14, 15, 31),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_017',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 25000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'transport',
        categoryLabel: 'Di chuyển',
        categoryIcon: '🚌',
        note: 'Xe buýt đi chơi cuối tuần',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 15, 10, 0),
        createdAt: DateTime(year, month, 15, 10, 1),
        updatedAt: DateTime(year, month, 15, 10, 1),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_018',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 350000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'sports',
        categoryLabel: 'Thể thao',
        categoryIcon: '⚽',
        note: 'Thuê sân cầu lông giờ vàng',
        source: 'manual',
        merchantName: 'Sân cầu lông Tân Phú',
        dateTs: DateTime(year, month, 16, 18, 0),
        createdAt: DateTime(year, month, 16, 18, 5),
        updatedAt: DateTime(year, month, 16, 18, 5),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_019',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 90000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'food_drink',
        categoryLabel: 'Ăn uống',
        categoryIcon: '🍜',
        note: 'Lẩu ăn tối cùng gia đình',
        source: 'manual',
        merchantName: 'Nhà hàng Lẩu Thái',
        dateTs: DateTime(year, month, 17, 19, 0),
        createdAt: DateTime(year, month, 17, 19, 5),
        updatedAt: DateTime(year, month, 17, 19, 5),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_020',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 18000,
        currency: 'VND',
        type: 'expense',
        categoryKey: 'snack',
        categoryLabel: 'Ăn vặt',
        categoryIcon: '🍿',
        note: 'Xúc xích xiên que cổng trường',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 18, 17, 30),
        createdAt: DateTime(year, month, 18, 17, 31),
        updatedAt: DateTime(year, month, 18, 17, 31),
        ocrUsed: false,
        ocrConfidence: null,
      ),

      // ── INCOME ───────────────────────────────────────────────
      TransactionModel(
        transactionId: 'txn_021',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 500000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'allowance',
        categoryLabel: 'Tiền tiêu vặt',
        categoryIcon: '💰',
        note: 'Ba mẹ cho tiền tiêu tháng 5',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 1, 8, 0),
        createdAt: DateTime(year, month, 1, 8, 1),
        updatedAt: DateTime(year, month, 1, 8, 1),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_022',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 200000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'gift',
        categoryLabel: 'Quà tặng',
        categoryIcon: '🎁',
        note: 'Tiền mừng sinh nhật từ cô',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 3, 10, 0),
        createdAt: DateTime(year, month, 3, 10, 2),
        updatedAt: DateTime(year, month, 3, 10, 2),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_023',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 150000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'allowance',
        categoryLabel: 'Tiền tiêu vặt',
        categoryIcon: '💰',
        note: 'Ba thưởng vì học tốt',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 5, 18, 0),
        createdAt: DateTime(year, month, 5, 18, 1),
        updatedAt: DateTime(year, month, 5, 18, 1),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_024',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 300000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'part_time',
        categoryLabel: 'Làm thêm',
        categoryIcon: '💼',
        note: 'Lương tutoring toán cho bé hàng xóm',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 10, 11, 0),
        createdAt: DateTime(year, month, 10, 11, 2),
        updatedAt: DateTime(year, month, 10, 11, 2),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_025',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 100000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'gift',
        categoryLabel: 'Quà tặng',
        categoryIcon: '🎁',
        note: 'Tiền lì xì từ chú',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 11, 9, 0),
        createdAt: DateTime(year, month, 11, 9, 1),
        updatedAt: DateTime(year, month, 11, 9, 1),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_026',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 50000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'reward',
        categoryLabel: 'Phần thưởng',
        categoryIcon: '🏆',
        note: 'Giải nhì thi Olympic Toán cấp trường',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 13, 16, 0),
        createdAt: DateTime(year, month, 13, 16, 5),
        updatedAt: DateTime(year, month, 13, 16, 5),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_027',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 500000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'allowance',
        categoryLabel: 'Tiền tiêu vặt',
        categoryIcon: '💰',
        note: 'Mẹ cho tiền giữa tháng',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 15, 8, 0),
        createdAt: DateTime(year, month, 15, 8, 1),
        updatedAt: DateTime(year, month, 15, 8, 1),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_028',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 250000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'part_time',
        categoryLabel: 'Làm thêm',
        categoryIcon: '💼',
        note: 'Thiết kế poster cho sự kiện lớp',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 16, 20, 0),
        createdAt: DateTime(year, month, 16, 20, 2),
        updatedAt: DateTime(year, month, 16, 20, 2),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_029',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 80000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'saving_interest',
        categoryLabel: 'Lãi tiết kiệm',
        categoryIcon: '🏦',
        note: 'Lãi heo đất cuối tháng',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 18, 10, 0),
        createdAt: DateTime(year, month, 18, 10, 2),
        updatedAt: DateTime(year, month, 18, 10, 2),
        ocrUsed: false,
        ocrConfidence: null,
      ),
      TransactionModel(
        transactionId: 'txn_030',
        userId: _userId,
        familyId: _familyId,
        amountMinor: 120000,
        currency: 'VND',
        type: 'income',
        categoryKey: 'gift',
        categoryLabel: 'Quà tặng',
        categoryIcon: '🎁',
        note: 'Tiền thưởng hoàn thành nhiệm vụ nhà',
        source: 'manual',
        merchantName: null,
        dateTs: DateTime(year, month, 19, 18, 30),
        createdAt: DateTime(year, month, 19, 18, 31),
        updatedAt: DateTime(year, month, 19, 18, 31),
        ocrUsed: false,
        ocrConfidence: null,
      ),
    ];
}

